spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/root
    username: root
    password: analsroqkf22*
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 10
      max-total: 10
      max-idle: 10
      min-idle: 10

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    show-sql: true

  thymeleaf:
    cache: false
